### PR TITLE
Add home server statistics

### PR DESCRIPTION
**Pull request by sj14**
Hi 👋

My organization is using the exporter but we also needed the statistics for homer servers.
I've implemented those changes and would like to merge the changes back to upstream.

And a big "thank you" for the exporter as It's a really helpful tool for us.

### CODE REVIEW

**Comment by gen2brain** [comment]
Hello, can you please just send that (home-server) as PR? It is very difficult to see where you added that support, why are config files from FR there, what is with docker-compose, brew, etc.

**Comment by sj14** [comment]
Yes, sorry. This was part of my local development setup which I thought would be useful too, but this could also be added in a separate PR.

I've now included only the necessary parts.

**Comment by gen2brain** [comment]
Merged, thanks!

**Comment by sj14** [comment]
Thanks for merging. Will there be a new release with the changes? :)

**Comment by gen2brain** [comment]
Yes, I will release it soon.

**Pull request merged**
