### PR TITLE
Add docker compose, docker ignore files

### PR DESCRIPTION
**Pull request by shatovilya**
Hey!
Added launch via docker + docker ignore to the project so that unnecessary files do not get into the docker image

### CODE REVIEW

**Comment by gen2brain** [comment]
What is the reason you want to add these files? There is already a Dockerfile in the repo, that builds "from scratch", i.e. just binary.

**Comment by shatovilya** [comment]
I always consider the presence of a docker ignore file to be necessary, even if the final image is scratch. This is a reduction of the image, and a safety net that the critical files will not fall into the intermediate or final image. Docker-compsoe allows you to quickly deploy a service by connecting the project as a git module.

**Comment by gen2brain** [comment]
In this case, there is no reduction so the file seems just like cruft that doesn't do anything. As for docker-compose, that is more suitable for other repo, the one that will be deployed, used, etc. doesn't add value here it seems. Sorry, not merging.

**Comment by shatovilya** [comment]
@gen2brain ok!

**Pull request closed without merging**
